version: 2
updates:
  # JavaScript/TypeScript dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "phlowai/maintainers"
    assignees:
      - "phlowai/maintainers"
    commit-message:
      prefix: "npm"
      include: "scope"

  # JavaScript/TypeScript - phlow-auth-js
  - package-ecosystem: "npm"
    directory: "/packages/phlow-auth-js"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5

  # JavaScript/TypeScript - phlow-cli
  - package-ecosystem: "npm"
    directory: "/packages/phlow-cli"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5

  # JavaScript/TypeScript - phlow-dev
  - package-ecosystem: "npm"
    directory: "/packages/phlow-dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5

  # JavaScript/TypeScript - integration tests
  - package-ecosystem: "npm"
    directory: "/tests/integration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5

  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/packages/phlow-auth-python"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "phlowai/maintainers"
    assignees:
      - "phlowai/maintainers"
    commit-message:
      prefix: "pip"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "phlowai/maintainers"
    assignees:
      - "phlowai/maintainers"
    commit-message:
      prefix: "actions"