site_name: Phlow
site_description: A2A Protocol extension with Supabase superpowers
site_url: https://prassanna-ravishankar.github.io/phlow/
repo_url: https://github.com/prassanna-ravishankar/phlow
repo_name: prassanna-ravishankar/phlow

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Guides:
    - Installation: installation.md
    - Configuration: configuration.md
    - Authentication: guides/authentication.md
    - Making Agent Calls: guides/agent-calls.md
  - Concepts:
    - How Phlow Works: concepts/how-it-works.md
    - A2A Protocol Integration: concepts/a2a-integration.md
  - Reference:
    - JavaScript API: api/javascript.md
    - Python API: api/python.md
  - Examples:
    - Basic Agent: examples/basic-agent.md
    - Multi-Agent Network: examples/multi-agent.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - tables

plugins:
  - search