site_name: Phlow
site_description: A2A Protocol Framework for AI Agents
site_url: https://prassanna-ravishankar.github.io/phlow
repo_url: https://github.com/prassanna-ravishankar/phlow
repo_name: prassanna-ravishankar/phlow

theme:
  name: material
  palette:
    primary: blue
    accent: cyan
  features:
    - navigation.tabs
    - content.code.copy

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Examples:
    - Simple Agent: examples/simple/README.md
    - Multi-Agent: examples/multi-agent/README.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search