name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '20'
  PYTHON_VERSION: '3.11'

jobs:
  # Lint and format checks
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint JavaScript/TypeScript
        run: npm run lint

      - name: Check TypeScript types
        run: npm run typecheck

      - name: Setup Python and uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true

      - name: Install Python dependencies
        run: |
          cd packages/phlow-auth-python
          uv sync --extra dev

      - name: Lint Python code
        run: |
          cd packages/phlow-auth-python
          uv run black --check src tests
          uv run isort --check-only src tests
          uv run flake8 src tests

      # Temporarily disabled due to a2a-sdk compatibility issues
      # - name: Type check Python code
      #   run: |
      #     cd packages/phlow-auth-python
      #     uv run mypy src

  # Unit tests
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - language: "javascript"
            node-version: "18"
          - language: "javascript" 
            node-version: "20"
          - language: "python"
            python-version: "3.10"
          - language: "python"
            python-version: "3.11"
            
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        if: matrix.language == 'javascript'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Setup Python and uv
        if: matrix.language == 'python'
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install JavaScript dependencies
        if: matrix.language == 'javascript'
        run: npm ci

      - name: Install Python dependencies
        if: matrix.language == 'python'
        run: |
          cd packages/phlow-auth-python
          uv sync --extra dev

      - name: Run JavaScript tests
        if: matrix.language == 'javascript'
        run: npm test

      - name: Run Python tests
        if: matrix.language == 'python'
        run: |
          cd packages/phlow-auth-python
          uv run pytest --cov=src --cov-report=xml --cov-report=term-missing

  # Build packages
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup Python and uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true

      - name: Install dependencies
        run: npm ci

      - name: Build JavaScript packages
        run: npm run build

      - name: Build Python package
        run: |
          cd packages/phlow-auth-python
          uv build