name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: "3.11"

    - name: Install dependencies
      run: |
        uv sync --extra fastapi --extra rbac --extra redis --extra monitoring --extra examples --dev

    - name: Check documentation links
      run: |
        # Check that all referenced files exist
        python -c "
        import os

        # Check README links
        readme_exists = os.path.exists('README.md')
        docs_dir_exists = os.path.exists('docs/')
        examples_exists = os.path.exists('examples/')

        print(f'✅ README.md exists: {readme_exists}')
        print(f'✅ docs/ exists: {docs_dir_exists}')
        print(f'✅ examples/ exists: {examples_exists}')

        if not all([readme_exists, docs_dir_exists, examples_exists]):
            exit(1)
        "

    - name: Validate examples comprehensively
      run: |
        uv run python scripts/validate-examples-ci.py
