name: Release (Tag-based)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  id-token: write

env:
  NODE_VERSION: '20'
  PYTHON_VERSION: '3.11'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup Python and uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update package versions
        run: |
          # Update JavaScript package version
          cd packages/phlow-auth-js
          npm version ${{ steps.version.outputs.VERSION }} --no-git-tag-version
          
          # Update Python package version
          cd ../phlow-auth-python
          sed -i 's/version = "[^"]*"/version = "${{ steps.version.outputs.VERSION }}"/' pyproject.toml
          
          # Return to root
          cd ../..

      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          
          # Build packages first
          npm run build
          
          # Publish JavaScript package
          cd packages/phlow-auth-js && npm publish --access public

      - name: Build and publish Python package
        run: |
          cd packages/phlow-auth-python
          uv sync --extra dev
          uv build
          uv run twine upload dist/* --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: Release v${{ steps.version.outputs.VERSION }}
          body: |
            ## Phlow ${{ steps.version.outputs.VERSION }}
            
            ### JavaScript Package
            - phlow-auth@${{ steps.version.outputs.VERSION }} (npm)
            
            ### Python Package
            - phlow-auth@${{ steps.version.outputs.VERSION }} (PyPI)
            
            Published to npm and PyPI.
          draft: false
          prerelease: false
          generate_release_notes: true