name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv sync --all-extras --dev
    
    - name: Run linting
      run: |
        uv run task lint
        uv run task format-check
        uv run task type-check
    
    - name: Run unit tests
      run: |
        uv run task test-ci
      env:
        # Mock environment variables for testing
        SUPABASE_URL: http://mock-supabase.local
        SUPABASE_ANON_KEY: mock-anon-key-for-testing
        AGENT_ID: test-agent
        AGENT_NAME: Test Agent
        AGENT_DESCRIPTION: Test agent for CI
        AGENT_PERMISSIONS: read:test,write:test
        AGENT_PUBLIC_KEY: mock-public-key
        AGENT_PRIVATE_KEY: mock-private-key
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false


  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv sync --all-extras --dev
    
    - name: Run linting
      run: |
        uv run task lint
        uv run task format-check
    
    - name: Type checking
      run: |
        uv run task type-check